#!/bin/bash
################################################################################
# Master Deployment Script - AI-Powered Insurance Claims Processing
#
# This script orchestrates the complete deployment of the insurance claims
# processing system on AWS EKS with dynamic configuration detection.
#
# Usage:
#   ./scripts/deploy.sh [OPTIONS]
#
# Options:
#   --terraform-only    Deploy only infrastructure via Terraform
#   --apps-only         Deploy only Kubernetes applications
#   --data-only         Load only sample data
#   --skip-data         Skip loading sample data
#   --policies N        Number of policies to generate (default: 500)
#   --claims N          Number of claims to generate (default: 100)
#   --help              Show this help message
#
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default configuration
DEPLOY_TERRAFORM=true
DEPLOY_APPS=true
LOAD_DATA=true
NUM_POLICIES=500
NUM_CLAIMS=100

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

################################################################################
# Functions
################################################################################

log_info() {
    echo -e "${BLUE}ℹ ${NC}$1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

show_help() {
    sed -n '2,/^$/p' "$0" | sed 's/^# //; s/^#//'
    exit 0
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    local missing_tools=()

    command -v aws >/dev/null 2>&1 || missing_tools+=("aws-cli")
    command -v kubectl >/dev/null 2>&1 || missing_tools+=("kubectl")
    command -v terraform >/dev/null 2>&1 || missing_tools+=("terraform")
    command -v docker >/dev/null 2>&1 || missing_tools+=("docker")
    command -v jq >/dev/null 2>&1 || missing_tools+=("jq")

    if [ ${#missing_tools[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing_tools[*]}"
        echo ""
        echo "Please install missing tools:"
        echo "  macOS:   brew install ${missing_tools[*]}"
        echo "  Ubuntu:  sudo apt-get install ${missing_tools[*]}"
        exit 1
    fi

    log_success "All prerequisites installed"
}

detect_aws_config() {
    log_info "Detecting AWS configuration..."

    # Get AWS account ID
    export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")
    if [ -z "$AWS_ACCOUNT_ID" ]; then
        log_error "Unable to determine AWS account ID. Please configure AWS credentials."
        exit 1
    fi

    # Get AWS region
    export AWS_REGION=$(aws configure get region 2>/dev/null || echo "us-west-2")

    # Set ECR registry
    export ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

    log_success "AWS Account ID: $AWS_ACCOUNT_ID"
    log_success "AWS Region: $AWS_REGION"
    log_success "ECR Registry: $ECR_REGISTRY"
}

detect_eks_cluster() {
    log_info "Detecting EKS cluster..."

    # Check if kubectl is already configured
    EKS_CLUSTER=$(kubectl config current-context 2>/dev/null | grep -o 'agentic-eks-cluster\|insurance-eks' || echo "")

    if [ -z "$EKS_CLUSTER" ]; then
        log_warning "No EKS cluster context found. Will be created by Terraform."
        export EKS_CLUSTER_NAME="agentic-eks-cluster"
    else
        export EKS_CLUSTER_NAME="$EKS_CLUSTER"
        log_success "Found EKS cluster: $EKS_CLUSTER_NAME"
    fi
}

deploy_infrastructure() {
    log_info "Deploying infrastructure with Terraform..."

    cd "${PROJECT_ROOT}/infrastructure/terraform"

    # Initialize Terraform if needed
    if [ ! -d ".terraform" ]; then
        log_info "Initializing Terraform..."
        terraform init
    fi

    # Create terraform.tfvars with detected values
    cat > terraform.tfvars <<EOF
# Auto-generated by deploy.sh - $(date)
aws_region         = "${AWS_REGION}"
cluster_name       = "${EKS_CLUSTER_NAME}"
vpc_cidr          = "10.0.0.0/16"
environment       = "production"

tags = {
  Environment = "production"
  Project     = "insurance-claims-processing"
  ManagedBy   = "terraform"
}
EOF

    log_info "Running terraform plan..."
    terraform plan -out=tfplan

    log_info "Applying terraform configuration..."
    terraform apply tfplan

    # Update kubeconfig
    log_info "Updating kubeconfig..."
    aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    cd "${PROJECT_ROOT}"
    log_success "Infrastructure deployed successfully"
}

build_and_push_images() {
    log_info "Building and pushing Docker images..."

    # Login to ECR
    log_info "Logging into ECR..."
    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    # Ensure ECR repositories exist
    log_info "Creating ECR repositories if needed..."
    local repos=("web-interface" "coordinator" "shared-memory" "policy-agent" "external-integrations" "claims-simulator")

    for repo in "${repos[@]}"; do
        aws ecr describe-repositories --repository-names "insurance-claims/${repo}" --region $AWS_REGION 2>/dev/null || \
        aws ecr create-repository --repository-name "insurance-claims/${repo}" --region $AWS_REGION >/dev/null
    done

    # Build and push images
    cd "${PROJECT_ROOT}"
    bash "${SCRIPT_DIR}/build-docker-images.sh"

    log_success "Docker images built and pushed"
}

deploy_kubernetes_apps() {
    log_info "Deploying Kubernetes applications..."

    cd "${PROJECT_ROOT}/infrastructure/kubernetes"

    # Update image references in manifests dynamically
    log_info "Updating Kubernetes manifests with current ECR registry..."
    find . -name "*.yaml" -type f -exec sed -i.bak "s|image: [0-9]*\.dkr\.ecr\.[a-z0-9-]*\.amazonaws\.com|image: ${ECR_REGISTRY}|g" {} \;

    # Deploy in order
    log_info "Deploying infrastructure components..."
    kubectl apply -f mongodb-deployment.yaml
    kubectl apply -f redis-deployment.yaml
    kubectl apply -f ollama-deployment.yaml

    log_info "Waiting for infrastructure to be ready..."
    kubectl wait --for=condition=ready pod -l app=mongodb -n insurance-claims --timeout=300s
    kubectl wait --for=condition=ready pod -l app=redis -n insurance-claims --timeout=300s

    log_info "Deploying application services..."
    kubectl apply -f shared-memory.yaml
    kubectl apply -f coordinator.yaml
    kubectl apply -f policy-agent.yaml
    kubectl apply -f external-integrations.yaml
    kubectl apply -f claims-web-interface.yaml
    kubectl apply -f claims-simulator.yaml

    log_info "Deploying ingress..."
    kubectl apply -f insurance-claims-ingress.yaml

    log_info "Waiting for all deployments..."
    kubectl wait --for=condition=available deployment --all -n insurance-claims --timeout=600s

    cd "${PROJECT_ROOT}"
    log_success "Kubernetes applications deployed successfully"
}

load_sample_data() {
    log_info "Loading sample data (${NUM_POLICIES} policies, ${NUM_CLAIMS} claims)..."

    cd "${PROJECT_ROOT}"

    # Update load-sample-data.sh with parameters
    bash scripts/load-data.sh --policies $NUM_POLICIES --claims $NUM_CLAIMS

    log_success "Sample data loaded successfully"
}

get_application_url() {
    log_info "Retrieving application URL..."

    local alb_hostname=$(kubectl get ingress insurance-claims-ingress -n insurance-claims -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")

    if [ -z "$alb_hostname" ]; then
        log_warning "ALB not yet provisioned. Run this command later to get the URL:"
        echo "  kubectl get ingress insurance-claims-ingress -n insurance-claims"
    else
        export APPLICATION_URL="http://${alb_hostname}"
        log_success "Application URL: $APPLICATION_URL"
    fi
}

show_summary() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${GREEN}Deployment Complete!${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Configuration:"
    echo "  AWS Account:     $AWS_ACCOUNT_ID"
    echo "  Region:          $AWS_REGION"
    echo "  EKS Cluster:     $EKS_CLUSTER_NAME"
    echo "  ECR Registry:    $ECR_REGISTRY"
    echo ""
    if [ -n "$APPLICATION_URL" ]; then
        echo "Access your application at:"
        echo "  $APPLICATION_URL"
        echo ""
        echo "Portals:"
        echo "  Claimant:    ${APPLICATION_URL}/claimant"
        echo "  Adjuster:    ${APPLICATION_URL}/adjuster"
        echo "  SIU:         ${APPLICATION_URL}/siu"
        echo "  Supervisor:  ${APPLICATION_URL}/supervisor"
    fi
    echo ""
    echo "Sample Data:"
    echo "  Policies: $NUM_POLICIES"
    echo "  Claims:   $NUM_CLAIMS"
    echo ""
    echo "Next Steps:"
    echo "  1. Access the web interface using the URL above"
    echo "  2. Check application logs: kubectl logs -n insurance-claims -l app=web-interface"
    echo "  3. Monitor metrics in the Supervisor Portal"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

################################################################################
# Main Script
################################################################################

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --terraform-only)
                DEPLOY_APPS=false
                LOAD_DATA=false
                shift
                ;;
            --apps-only)
                DEPLOY_TERRAFORM=false
                shift
                ;;
            --data-only)
                DEPLOY_TERRAFORM=false
                DEPLOY_APPS=false
                shift
                ;;
            --skip-data)
                LOAD_DATA=false
                shift
                ;;
            --policies)
                NUM_POLICIES="$2"
                shift 2
                ;;
            --claims)
                NUM_CLAIMS="$2"
                shift 2
                ;;
            --help)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                ;;
        esac
    done

    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "${BLUE}  AI-Powered Insurance Claims Processing System${NC}"
    echo -e "${BLUE}  Automated Deployment${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Pre-flight checks
    check_prerequisites
    detect_aws_config
    detect_eks_cluster

    # Execute deployment steps
    if [ "$DEPLOY_TERRAFORM" = true ]; then
        deploy_infrastructure
    fi

    if [ "$DEPLOY_APPS" = true ]; then
        build_and_push_images
        deploy_kubernetes_apps
    fi

    if [ "$LOAD_DATA" = true ]; then
        load_sample_data
    fi

    # Get application URL
    get_application_url

    # Show summary
    show_summary
}

# Run main function
main "$@"
